// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    PokemonCard: typeof import('./src/components/PokemonCard.vue')['default']
    SelectorPokemon: typeof import('./src/components/SelectorPokemon.vue')['default']
    SidebarComponent: typeof import('./src/components/SidebarComponent.vue')['default']
    'SidebarComponent copy': typeof import('./src/components/SidebarComponent copy.vue')['default']
    TestComponent: typeof import('./src/components/TestComponent.vue')['default']
  }
}

export { }
